-- Phase 11 Part 2: IT General Controls and Additional Procedures

-- Insert IT General Controls Procedures
INSERT INTO audit_procedures (firm_id, procedure_code, procedure_name, category, objective, estimated_hours, risk_level, procedure_type, is_active, instructions, evidence_requirements, sample_size_guidance)
SELECT 
  f.id,
  p.procedure_code,
  p.procedure_name,
  p.category,
  p.objective,
  p.estimated_hours,
  p.risk_level,
  p.procedure_type,
  true,
  jsonb_build_object('type', 'doc', 'content', jsonb_build_array(jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', p.instructions))))),
  jsonb_build_array(p.evidence_req),
  p.sample_guidance
FROM firms f
CROSS JOIN (
  VALUES
    -- Access Controls (8 procedures)
    ('ITGC-100', 'User Access Provisioning', 'Access Controls', 'Test user access request and approval process', 3, 'high', 'Control Testing', 'Review access provisioning procedures. Test sample of new user access requests for proper authorization. Verify segregation of duties in approval process. Confirm appropriate level of access granted.', 'Access request forms, approval emails, system logs', '25 new user accounts'),
    ('ITGC-101', 'User Access Deprovisioning', 'Access Controls', 'Test timely removal of access for terminated users', 3, 'high', 'Control Testing', 'Obtain list of terminated employees. Verify access was removed timely (same day or next business day). Test across all critical systems. Identify any delays or failures to remove access.', 'HR termination list, system access reports, deprovisioning tickets', 'All terminations in period'),
    ('ITGC-102', 'Periodic Access Reviews', 'Access Controls', 'Test management review of user access rights', 4, 'high', 'Control Testing', 'Review access certification procedures. Test sample of access reviews for completeness and timeliness. Verify inappropriate access is identified and removed. Assess management follow-up on exceptions.', 'Access review certifications, remediation documentation', '3-4 quarterly reviews'),
    ('ITGC-103', 'Privileged Access Management', 'Access Controls', 'Test controls over privileged and administrative access', 4, 'high', 'Control Testing', 'Identify users with elevated privileges. Verify appropriate approval and business justification. Test monitoring of privileged account usage. Review privileged access provisioning and periodic reviews.', 'Privileged user listing, approval documentation, activity logs', 'All privileged accounts'),
    ('ITGC-104', 'Password Policy Controls', 'Access Controls', 'Test password policy configuration and enforcement', 2, 'medium', 'Control Testing', 'Review password policy requirements. Test system configuration for complexity, length, expiration, and history requirements. Verify policies align with security standards.', 'Password policy documentation, system configurations', 'All critical systems'),
    ('ITGC-105', 'Multi-Factor Authentication', 'Access Controls', 'Verify MFA implementation for sensitive systems', 2, 'high', 'Control Testing', 'Review MFA implementation. Test that MFA is required for remote access and privileged accounts. Verify MFA cannot be bypassed. Test enrollment and exception processes.', 'MFA configuration, authentication logs, policy documentation', 'Critical systems and remote access'),
    ('ITGC-106', 'Segregation of Duties', 'Access Controls', 'Test for incompatible access combinations', 3, 'high', 'Control Testing', 'Review SoD matrix. Test user access against SoD conflicts. Identify users with incompatible access. Assess compensating controls for identified conflicts. Test monitoring of SoD violations.', 'SoD matrix, user access reports, compensating control evidence', 'All users with financial access'),
    ('ITGC-107', 'Service Account Management', 'Access Controls', 'Test controls over service and system accounts', 3, 'medium', 'Control Testing', 'Identify all service accounts. Verify proper authorization and documentation. Test that service accounts use complex passwords and are excluded from expiration policies. Review activity monitoring.', 'Service account inventory, approval documentation, password policies', 'All service accounts'),
    
    -- Change Management (6 procedures)
    ('ITGC-200', 'Change Request Process', 'Change Management', 'Test change request and approval procedures', 3, 'high', 'Control Testing', 'Review change management procedures. Test sample of changes for proper documentation, business justification, and authorization. Verify change classification (emergency, standard, normal).', 'Change tickets, approval documentation, change policies', '25-30 changes across types'),
    ('ITGC-201', 'Development Testing Requirements', 'Change Management', 'Test development and testing procedures', 3, 'medium', 'Control Testing', 'Review testing requirements and procedures. Test sample of changes for evidence of testing prior to production release. Verify test results are documented and issues resolved.', 'Test plans, test results, defect logs', '20 changes'),
    ('ITGC-202', 'Production Migration Controls', 'Change Management', 'Test production deployment controls and procedures', 4, 'high', 'Control Testing', 'Review deployment procedures. Test sample of production migrations for proper approval, deployment documentation, and segregation of duties. Verify back-out plans exist.', 'Deployment checklists, approval records, migration documentation', '20-25 deployments'),
    ('ITGC-203', 'Emergency Change Procedures', 'Change Management', 'Test emergency change procedures and post-implementation review', 2, 'high', 'Control Testing', 'Review emergency change procedures. Test sample of emergency changes for appropriate authorization and post-implementation review. Verify emergency changes are justified and documented.', 'Emergency change tickets, approval records, PIR documentation', 'All emergency changes'),
    ('ITGC-204', 'Change Environment Management', 'Change Management', 'Test segregation between development, test, and production', 3, 'high', 'Control Testing', 'Verify separate environments exist. Test that production changes come from controlled source code. Verify developers do not have production access. Test controls preventing unauthorized migration.', 'Environment documentation, access reports, migration logs', 'All critical systems'),
    ('ITGC-205', 'Version Control', 'Change Management', 'Test use of version control systems', 2, 'medium', 'Control Testing', 'Verify code is maintained in version control. Test that production releases come from version control. Review branching and merging procedures. Test code review requirements.', 'Version control policies, commit logs, code review records', 'Sample of recent code changes'),
    
    -- Computer Operations (6 procedures)
    ('ITGC-300', 'Backup Procedures', 'Computer Operations', 'Test data backup procedures and monitoring', 3, 'high', 'Control Testing', 'Review backup policies and schedules. Test backup monitoring and exception follow-up. Verify backups are encrypted and stored securely. Test backup success rates and storage locations.', 'Backup policies, backup logs, monitoring reports', 'One month of backup operations'),
    ('ITGC-301', 'Backup Restoration Testing', 'Computer Operations', 'Test periodic restoration testing of backups', 3, 'high', 'Control Testing', 'Review restoration testing procedures. Test sample of restoration tests for completeness and success. Verify restoration testing covers critical systems and occurs at required frequency.', 'Restoration test results, test schedules, success metrics', 'Restoration tests for audit period'),
    ('ITGC-302', 'Job Scheduling and Monitoring', 'Computer Operations', 'Test batch job scheduling and failure monitoring', 2, 'medium', 'Control Testing', 'Review batch job schedules and dependencies. Test monitoring of job failures and exception handling. Verify critical jobs are monitored and failures are investigated timely.', 'Job schedules, monitoring logs, incident tickets', 'One month of batch operations'),
    ('ITGC-303', 'Incident Management', 'Computer Operations', 'Test incident detection, response, and resolution', 3, 'high', 'Control Testing', 'Review incident management procedures. Test sample of incidents for timely detection, proper categorization, and resolution. Verify root cause analysis for critical incidents.', 'Incident tickets, resolution documentation, RCA reports', '20-25 incidents including critical'),
    ('ITGC-304', 'Capacity Management', 'Computer Operations', 'Test system capacity monitoring and planning', 2, 'medium', 'Control Testing', 'Review capacity monitoring procedures. Test that capacity is monitored and alerts are configured. Verify capacity planning occurs and capacity issues are addressed proactively.', 'Capacity reports, alert configurations, capacity plans', 'Recent capacity reviews'),
    ('ITGC-305', 'Vulnerability Management', 'Computer Operations', 'Test vulnerability scanning and patching procedures', 4, 'high', 'Control Testing', 'Review vulnerability management procedures. Test vulnerability scanning frequency and coverage. Verify critical vulnerabilities are remediated timely per policy. Test patch management process.', 'Vulnerability scan reports, remediation tracking, patch logs', 'One quarter of vulnerability operations'),
    
    -- Business Continuity (5 procedures)
    ('ITGC-400', 'Disaster Recovery Plan', 'Business Continuity', 'Review and test disaster recovery planning', 3, 'high', 'Control Testing', 'Review disaster recovery plans for completeness and currency. Verify plans are updated annually. Assess adequacy of recovery time and point objectives. Review plan distribution and storage.', 'DR plans, plan review documentation, RTOs/RPOs', 'All critical systems'),
    ('ITGC-401', 'DR Testing', 'Business Continuity', 'Test disaster recovery testing procedures', 4, 'high', 'Control Testing', 'Review DR testing procedures. Test sample of DR tests for completeness and success. Verify critical systems are tested at required frequency. Review lessons learned and remediation of test failures.', 'DR test results, test schedules, remediation plans', 'DR tests during audit period'),
    ('ITGC-402', 'Data Center Controls', 'Business Continuity', 'Test physical security and environmental controls', 3, 'medium', 'Control Testing', 'Review data center security procedures. Test physical access controls and monitoring. Verify environmental controls (HVAC, fire suppression, power). Review visitor logs and access reports.', 'Access logs, environmental monitoring, visitor logs', 'One quarter of access events'),
    ('ITGC-403', 'Business Impact Analysis', 'Business Continuity', 'Review business impact analysis and criticality ratings', 2, 'medium', 'Substantive', 'Review business impact analysis documentation. Verify critical systems are identified. Assess reasonableness of RTOs and RPOs. Verify BIA is updated regularly.', 'BIA documentation, system criticality ratings', 'Full BIA review'),
    ('ITGC-404', 'Backup Site Readiness', 'Business Continuity', 'Test backup site/failover capabilities', 2, 'high', 'Control Testing', 'For entities with backup sites or cloud failover, review readiness procedures. Test failover capabilities during DR tests. Verify backup site has adequate capacity and current data.', 'Backup site documentation, failover test results', 'Backup site reviews'),
    
    -- HIPAA Compliance Procedures (10 procedures)
    ('HIPAA-100', 'Security Risk Analysis', 'HIPAA Security', 'Review completion of security risk analysis', 4, 'high', 'Substantive', 'Review security risk analysis documentation. Verify analysis covers all ePHI systems and locations. Assess thoroughness of threat and vulnerability identification. Review risk mitigation plans.', 'Risk analysis documentation, risk register, mitigation plans', 'Full risk analysis review'),
    ('HIPAA-101', 'Access Controls - ePHI', 'HIPAA Security', 'Test access controls protecting ePHI', 4, 'high', 'Control Testing', 'Test unique user identification and emergency access procedures. Verify automatic logoff and encryption/decryption controls. Test that access is limited to minimum necessary.', 'Access logs, user provisioning records, system configurations', '25-30 user access reviews'),
    ('HIPAA-102', 'Audit Controls', 'HIPAA Security', 'Test audit logging of ePHI access and activity', 3, 'high', 'Control Testing', 'Verify audit logs capture access to ePHI. Test that logs are reviewed regularly for suspicious activity. Verify logs are protected from alteration. Test log retention meets requirements.', 'Audit log samples, log review documentation, retention policies', 'Sample of critical system logs'),
    ('HIPAA-103', 'Integrity Controls', 'HIPAA Security', 'Test controls ensuring ePHI is not improperly altered', 2, 'medium', 'Control Testing', 'Test mechanisms to authenticate ePHI. Verify controls prevent unauthorized modification or destruction. Test data backup and recovery procedures.', 'Authentication mechanisms, change logs, backup records', 'Critical ePHI systems'),
    ('HIPAA-104', 'Transmission Security', 'HIPAA Security', 'Test security of ePHI transmissions', 3, 'high', 'Control Testing', 'Verify encryption is used for ePHI transmission. Test integrity controls for transmitted data. Review network security measures. Test secure messaging systems.', 'Encryption configurations, transmission logs, network diagrams', 'All ePHI transmission methods'),
    ('HIPAA-105', 'Privacy Policies and Procedures', 'HIPAA Privacy', 'Review privacy policies and procedures', 3, 'medium', 'Substantive', 'Review all required privacy policies. Verify policies are current and comprehensive. Assess distribution of policies to workforce. Review policy update procedures.', 'Privacy policies, distribution records, update logs', 'All privacy policies'),
    ('HIPAA-106', 'Notice of Privacy Practices', 'HIPAA Privacy', 'Test distribution and acknowledgment of privacy notices', 2, 'medium', 'Control Testing', 'Review Notice of Privacy Practices for compliance. Test distribution to patients. Verify acknowledgments are obtained and documented. Test availability of notices.', 'NPP document, distribution procedures, acknowledgment records', '25 patient acknowledgments'),
    ('HIPAA-107', 'Individual Rights', 'HIPAA Privacy', 'Test processes for individual rights requests', 3, 'medium', 'Control Testing', 'Test access request procedures. Review amendment request handling. Test accounting of disclosures process. Verify timely responses to requests.', 'Request logs, response documentation, tracking system', 'Sample of requests by type'),
    ('HIPAA-108', 'Business Associate Agreements', 'HIPAA Privacy', 'Review business associate agreements', 3, 'high', 'Substantive', 'Identify all business associates. Verify executed BAAs are in place. Review BAAs for required provisions. Test monitoring of business associate compliance.', 'Business associate listing, BAAs, monitoring documentation', 'All business associates'),
    ('HIPAA-109', 'Breach Notification', 'HIPAA Privacy', 'Test breach identification and notification procedures', 2, 'medium', 'Control Testing', 'Review breach identification procedures. Test breach risk assessment process. Verify notification procedures meet timeline requirements. Review breach log.', 'Breach policies, risk assessment documentation, notification records', 'All breaches in period')
) AS p(procedure_code, procedure_name, category, objective, estimated_hours, risk_level, procedure_type, instructions, evidence_req, sample_guidance)
ON CONFLICT (firm_id, procedure_code) DO NOTHING;