// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

// DEMO MODE: Use service role key to bypass RLS
// TODO: Set to false for production
// NOTE: Set to false now that RLS policies are fixed
const DEMO_MODE = false;

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';
const SUPABASE_SERVICE_ROLE_KEY = import.meta.env.VITE_SUPABASE_SERVICE_ROLE_KEY || '';

// In demo mode, use service role key to bypass RLS; otherwise use anon key
const SUPABASE_KEY = DEMO_MODE && SUPABASE_SERVICE_ROLE_KEY ? SUPABASE_SERVICE_ROLE_KEY : SUPABASE_ANON_KEY;

// Export whether credentials are configured
export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_KEY && !SUPABASE_KEY.includes('YOUR_'));

// Check for missing environment variables
if (!isSupabaseConfigured) {
  console.error(
    '%c⚠️ Supabase Not Configured',
    'background: #ff6b6b; color: white; padding: 4px 8px; border-radius: 4px; font-weight: bold;',
    '\n\nPlease set the following environment variables in your .env file:',
    '\n- VITE_SUPABASE_URL',
    '\n- VITE_SUPABASE_ANON_KEY',
    '\n\nGet these values from: https://supabase.com/dashboard/project/otbviownvtbuatjsoezq/settings/api'
  );
}

if (DEMO_MODE) {
  console.info(
    '%c🎭 DEMO MODE ACTIVE',
    'background: #4CAF50; color: white; padding: 4px 8px; border-radius: 4px; font-weight: bold;',
    '\nUsing service role key to bypass RLS. Disable for production.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with valid or placeholder values (the app should handle unconfigured state)
export const supabase: SupabaseClient<Database> = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);